### ISSUE TITLE
Línea blanca inferior

### ISSUE THREAD

**Issue by jforni** [YPachado99/trabajoFinal-grupo5-FrontEnd#1]
Aparece una linea blanca en la parte inferior. 
Adjunto imagen:
![image](https://github.com/YPachado99/trabajoFinal-grupo5-FrontEnd/assets/6042663/122f678f-1fa7-4ff9-b7dd-c509b92c87d9)

**Comment by YPachado99** [comment]
la linea negra no iba. Solucionado
