### ISSUE TITLE
Alineación del precio

### ISSUE THREAD

**Issue by jforni** [YPachado99/trabajoFinal-grupo5-FrontEnd#2]
El precio baja de renglón cuando supera una cifra determinada. La idea es que el símbolo de la moneda con el valor queden en la misma línea.
Adjunto imagen:
![image](https://github.com/YPachado99/trabajoFinal-grupo5-FrontEnd/assets/6042663/2e6a299f-7268-4e24-98f9-f200455e856b)

**Comment by YPachado99** [comment]
Solucionado
