### ISSUE TITLE
Eliminación de usuarios

### ISSUE THREAD

**Issue by jforni** [YPachado99/trabajoFinal-grupo5-FrontEnd#4]
Al eliminar algún usuario, no pide la verificación de si se está seguro de eliminar el usuario seleccionado. Debería agregar una pregunta o verificación para evitar errores.
Además, permite eliminar usuarios administradores. Verificar que si se eliminan todos los usuarios administradores, no se podría ingresar al sistema.

**Comment by YPachado99** [comment]
agregado

**Comment by YPachado99** [comment]
agregado
