### ISSUE TITLE
Coherencia de idioma

### ISSUE THREAD

**Issue by jforni** [YPachado99/trabajoFinal-grupo5-FrontEnd#5]
Revisar que figura Home (inglés) pero el resto de los textos están en español. 
Reemplazar Home por Inicio.
Adjunto imagen:
![image](https://github.com/YPachado99/trabajoFinal-grupo5-FrontEnd/assets/6042663/338c9c3e-0f56-4697-bc1e-9d57924e3a98)

**Comment by YPachado99** [comment]
corregido
